#!/usr/bin/python

print('Print works with or without parenthesis')

#Now this file is made as execute file with out extens of .py
#In command line type "./file_name , before that make sure is in execute persmission
# chmod a+x file_name
#Execution: ./file_name

#If the script is made executable, the operating system will use that first line 
#to know which interpreter to run to parse the rest of the file to perform some action.

#If you always run these kinds of scripts from 
#the command line like python foo.py then you could remove the first line.

