#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan 13 19:40:12 2018

@author: star
"""

# Here you should write comments
print ('comments with #')
#This line is skipped by interpreter because it is after hash sign

'''
This is a multi line
comment
'''
print ("comments with ''' ")


"""
This is a multi line
comment
"""
print ('comments with """ ')

